
version: '3.8'
services:
  store:
    image: arm64v8/redis:alpine
    restart: always
    ports:
      - 127.0.0.1:${REDIS_PORT}:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASS}
    volumes:
      - store:/data
volumes:
  store:
    driver: local