"""default_conn_id

Revision ID: bb3394a86567
Revises: e70b248b96ff
Create Date: 2023-01-09 17:49:15.580703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb3394a86567'
down_revision = 'e70b248b96ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
